# Conexión a la Base de Datos con Plan B local si no detecta Railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST:host.docker.internal}:${MYSQLPORT:3306}/${MYSQLDATABASE:tiendadb}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:manchislindo}

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto dinámico de la nube (Si no existe usa el 8080)
server.port=${PORT:8080}

# Secreto de JWT con tu clave real como Plan B por si Railway no la lee
config.jwt.secret=${JWT_SECRET:OJctTbS6ZgLmNGDmFdDyjwqMJFhu3RfoTsvN3h9pmiCKTU5iUQelUfidEA5E}