# Si Railway inyecta SPRING_DATASOURCE_URL, la usa; si no, va al localhost de tu PC
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tiendadb}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:manchislindo}

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto dinámico de la nube (Si no existe usa el 8080)
server.port=${PORT:8080}

# Secreto de JWT con plan B local
config.jwt.secret=${JWT_SECRET:OJctTbS6ZgLmNGDmFdDyjwqMJFhu3RfoTsvN3h9pmiCKTU5iUQelUfidEA5E}