# Conexion dinámica a la base de datos de produccion (Railway)
spring.datasource.url=jdbc:mysql://${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuracion de Hibernate para producción
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Puerto dinamico asignado por el servidor de la nube (¡Obligatorio!)
server.port=${PORT:8080}

# Secreto de JWT para la firma de tokens
config.jwt.secret=OJctTbS6ZgLmNGDmFdDyjwqMJFhu3RfoTsvN3h9pmiCKTU5iUQelUfidEA5E